### ISSUE TITLE
Warn user if cookies disabled

### ISSUE THREAD

**Issue by TomiCake** [Wolkenberg-Gymnasium/StundenplanWebApp#22]
Beispiel Frau S: Cookies nicht zugelassen -> keine erfolgreiche Anmeldung -> kein Stundenplan

**Comment by Michael-Janke** [comment]
hab ich gemacht. Muss man aber mal testen ob der dialog auch kommt, wenn man offline ist.

**Comment by TomiCake** [comment]
Der Fehler tritt auch nur mit dieser Einstellung auf:

![image](https://user-images.githubusercontent.com/9019581/48651880-26b20a00-e9fd-11e8-8e57-89d7c4c6c491.png)

Wenn man Cookies komplett deaktiviert, kommt die Meldung von microsoft selbst.

**Comment by Michael-Janke** [comment]
ich weiß, das war bei frau M auch schon.

Hab ein dialog gemacht - der kommt wenn es ein TOKEN_ERROR gab. Der kann aber auch kommen, wenn man offline ist - müsste man mal checken, ob er dann auch kommt.

**Comment by Michael-Janke** [comment]
https://stackoverflow.com/questions/3550790/check-if-third-party-cookies-are-enabled

**Comment by TomiCake** [comment]
> Der kann aber auch kommen, wenn man offline ist

Das ist leider der Fall. Ich habe auch gesehen, dass das Problem in Teams auch besteht.

**Comment by TomiCake** [comment]
e6c641932c1b065c1cbc61e4a79ef1b991770fb1
